name: Gradle Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17']

    steps:
    - uses: actions/checkout@v3
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true
    
    - name: Execute Gradle build
      run: ./gradlew buildPlugin --stacktrace
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Upload Plugin Artifact
      uses: actions/upload-artifact@v3
      with:
        name: plugin-artifact
        path: build/distributions/dependency-viewer-${{ github.event.release.tag_name }}.zip
        retention-days: 0

    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/distributions/dependency-viewer-${{ github.event.release.tag_name }}.zip
        asset_name: dependency-viewer-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip 